---
assert_lefthook_installed: true
colors: true
pre-commit:
  jobs:
    - name: brakeman
      run: brakeman --no-pager --no-progress --quiet
    - name: broken-links
      run: lychee . --exclude http://localhost:3000 --exclude https://portal.azure.com  --exclude file://
    - name: bundle-audit
      run: bundle exec bundle-audit --update
    - name: bundle-outdated
      run: bundle outdated --strict
    - name: erblint
      run: bundle exec erb_lint app/views --lint-all
    - name: fasterer
      run: bundle exec fasterer
    - name: rustywind
      run: rustywind .
    - name: standardrb
      run: bundle exec standardrb
    - name: yamllint
      run: yamllint -c .yamllint .
    - name: zeitwork
      run: rake app:zeitwerk:check
