# frozen_string_literal: true

module Panda
  module CMS
    class Engine < ::Rails::Engine
      # Backtrace cleaner configuration for better error messages
      module BacktraceConfig
        extend ActiveSupport::Concern

        included do
          initializer "#{engine_name}.backtrace_cleaner" do |_app|
            engine_root_regex = Regexp.escape(root.to_s + File::SEPARATOR)

            # Clean those ERB lines, we don't need the internal autogenerated
            # ERB method, what we do need (line number in ERB file) is already there
            Rails.backtrace_cleaner.add_filter do |line|
              line.sub(/(\.erb:\d+):in `__.*$/, '\\1')
            end

            # Remove our own engine's path prefix, even if it's
            # being used from a local path rather than the gem directory.
            Rails.backtrace_cleaner.add_filter do |line|
              line.sub(/^#{engine_root_regex}/, "#{engine_name} ")
            end

            # Keep Umlaut's own stacktrace in the backtrace -- we have to remove Rails
            # silencers and re-add them how we want.
            Rails.backtrace_cleaner.remove_silencers!

            # Silence what Rails silenced, UNLESS it looks like
            # it's from Umlaut engine
            Rails.backtrace_cleaner.add_silencer do |line|
              (line !~ Rails::BacktraceCleaner::APP_DIRS_PATTERN) &&
                (line !~ /^#{engine_root_regex}/) &&
                (line !~ /^#{engine_name} /)
            end
          end
        end
      end
    end
  end
end
