# frozen_string_literal: true

source "https://rubygems.org"

gem "html-proofer", "~> 5.0", group: :development
gem "jekyll"
gem "jekyll-github-metadata", ">= 2.15"
gem "jekyll-include-cache", group: :jekyll_plugins
gem "jekyll-sitemap", group: :jekyll_plugins
gem "just-the-docs"
