---
name: "Debug Authentication Tests"

on:
  workflow_dispatch:
  push:
    branches:
      - devex/ci-improvements

jobs:
  debug-auth:
    name: "Debug Auth Tests"
    runs-on: "ubuntu-latest"
    env:
      BUNDLE_PATH: "vendor/bundle"
      RAILS_ENV: test
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: "actions/checkout@v4"
      - name: "Set timezone"
        run: |
          sudo timedatectl set-timezone Europe/London
      - name: "Install xvfb"
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb libvips
          export DISPLAY=':99.0'
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

      - name: "Setup Ruby"
        uses: "ruby/setup-ruby@v1"
        with:
          bundler-cache: true
      - name: "Setup test environment"
        env:
          DATABASE_URL: "postgres://postgres:password@localhost:5432/test"
          REDIS_URL: "redis://localhost:6379/0"
          RAILS_ENV: "test"
          PG_USER: "postgres"
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          PT_SILENCE_AR_COMPAT_WARNING: true
        run: |
          bundle exec rails db:create db:schema:load
      - name: "Run debug auth tests"
        env:
          DATABASE_URL: "postgres://postgres:password@localhost:5432/test"
          REDIS_URL: "redis://localhost:6379/0"
          RAILS_ENV: "test"
          PG_USER: "postgres"
          PANDA_CMS_USE_GITHUB_ASSETS: "true"
          CAPYBARA_ARTIFACTS: "../tmp/capybara"
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          PT_SILENCE_AR_COMPAT_WARNING: true
        run: |
          mkdir -p tmp
          xvfb-run -a bundle exec rspec \
            spec/system/panda/cms/admin/login_spec.rb:17 \
            spec/system/panda/cms/admin/login_spec.rb:57 \
            --format documentation \
            --color
      - name: Keep screenshots from failed system tests
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: debug-auth-screenshots
          path: ${{ github.workspace }}/spec/tmp/capybara
          if-no-files-found: ignore
      - name: Keep debug files from failed tests
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: debug-auth-files
          path: |
            ${{ github.workspace }}/spec/tmp/capybara/*.html
            ${{ github.workspace }}/spec/dummy/log/test.log
            ${{ github.workspace }}/tmp/capybara/**/*.png
            ${{ github.workspace }}/tmp/capybara/**/*.html
          if-no-files-found: ignore